<?php

/**
 * Returns the number of uses for this coupon. If any order references a coupon
 * that counts as a "use."
 *
 * @param $coupon_id
 *   Coupon id to check.
 *
 * @return integer
 *   Returns number of uses of the coupon in all orders.
 */
function commerce_coupon_usage_get_number_of_uses($coupon_id) {
  $query = new EntityFieldQuery();
  return $query
    ->entityCondition('entity_type', 'commerce_order')
    ->fieldCondition('commerce_coupons', 'target_id', $coupon_id, '=')
    ->count()
    ->execute();
}

/*
 * Implements hook_commerce_coupon_may_redeem_alter().
 */
function commerce_coupon_usage_commerce_coupon_coupon_may_redeem_alter(&$error, $coupon, $order) {
  $uses = commerce_coupon_usage_get_number_of_uses($coupon->coupon_id);
  $coupon_wrapper = entity_metadata_wrapper('commerce_coupon', $coupon);

  if ($coupon_wrapper->commerce_coupon_max_uses->value() && $uses >= $coupon_wrapper->commerce_coupon_max_uses->value()) {
    $error = t('Coupon has exceeded maximum number of uses.');
  }
}

/*
 * Implements hook_flush_caches().
 */
function commerce_coupon_usage_flush_caches() {
  module_load_install('commerce_coupon_usage');
  _commerce_coupon_install_helper();
}
