<?php

/*
 * Implements hook_menu().
 */
function commerce_coupon_update_menu() {
  $items['admin/commerce/coupons/update'] = array(
    'title' => 'Update',
    'description' => 'Update coupon entities from 1.x to 2.x compatibility.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_coupon_update_form'),
    'access arguments' => array('administer commerce_coupon entities')
  );
  
  return $items;
}

/*
 * Coupon update form
 */
function commerce_coupon_update_form() {
  drupal_set_title(t('Coupons 1.x to 2.x upgrade'));
  
  $form['explanation'] = array(
    '#type' => 'markup',
    '#markup' => t('Explanation ..')
  );
  
  $form['proceed'] = array(
    '#type' => 'submit',
    '#value' => t('Proceed'),    
  );
  
  return $form;
}

/*
 * Coupon update form submit
 */
function commerce_coupon_update_form_submit(&$form, &$form_state) {
  drupal_set_message(t('Updating coupons'));  
  $operations = array();
  
  // Load all coupon ids.
  $coupon_ids = db_query('SELECT coupon_id FROM {commerce_coupon}')->fetchCol();
  
  foreach ($coupon_ids as $coupon_id) {
    $operations[] = array('commerce_coupon_update_batch_worker', array($coupon_id));
  }
  
  if (!empty($operations)) {
    $batch = array(
      'operations' => $operations,
      'finished' => 'commerce_coupon_update_batch_finished'
    );
    
    batch_set($batch);
  }
}

/*
 * Implements hook_commerce_coupon_update_parameters().
 */
function commerce_coupon_update_commerce_coupon_update_parameters($coupon) {
  $coupon_wrapper = entity_metadata_wrapper('commerce_coupon', $coupon);
  
  // Return all of the necessary parameters for converting the coupon into a 
  // discount and an offer.
  switch ($coupon->type) {
    case 'commerce_coupon_pct':
      $offer_value = $coupon_wrapper->commerce_coupon_percent_amount->value();
      $offer_value_safe = str_replace('.', '', $offer_value);

      return array(
        'offer value' => $offer_value,
        'offer value safe' => $offer_value_safe,
        'label' => t('@pct percent discount', array('@pct' => $offer_value)),
        'discount name' => 'pct_discount_' . $offer_value_safe,
        'offer field' => 'commerce_percentage',
        'offer type' => 'percentage'
      );

      break;
    case 'commerce_coupon_fixed':
      $offer_price = $coupon_wrapper->commerce_coupon_fixed_amount->value();
      $offer_amount = $offer_price['amount'];
      $offer_price_formatted = commerce_currency_format($offer_amount, $offer_price['currency_code']);

      return array(
        'offer value' => $offer_price,
        'offer value safe' => $offer_amount,
        'label' => t('@pct discount', array('@pct' => $offer_price_formatted)),
        'discount name' => 'fixed_discount_' . $offer_amount,
        'offer field' => 'commerce_fixed_amount',
        'offer type' => 'fixed_amount'
      );

      break;
  }
}

/*
 * Batch worker callback: process a single coupon entity
 */
function commerce_coupon_update_batch_worker($coupon_id, &$context) {
  $coupon = commerce_coupon_load($coupon_id);
  if ($coupon) {
    $coupon_wrapper = entity_metadata_wrapper('commerce_coupon', $coupon);
    
    // Update code column.
    if (empty($coupon->code)) {
      $code = $coupon_wrapper->commerce_coupon_code->value();
      $coupon->code = $code;
    }

    // Find update information about this coupon type.
    $parameters = module_invoke_all('commerce_coupon_update_parameters', $coupon);
    if (empty($parameters)) {
      return;
    }   
    
    // Determine if there is a suitable discount to use.
    $query = new EntityFieldQuery;
    $results = $query
      ->entityCondition('entity_type', 'commerce_discount')
      ->propertyCondition('type', 'order_discount')
      ->propertyCondition('name', $parameters['discount name'])
      ->execute();    

    // Load matching discount.
    if (!empty($results['commerce_discount'])) {
      $discount_ids = array_keys($results['commerce_discount']);
      $discounts = entity_load('commerce_discount', $discount_ids);
      $discount = reset($discounts);
    }
    else {
      // Discount not found - create and save offer.
      $offer = entity_create('commerce_discount_offer', array(
        'type' => $parameters['offer type'],
      ));
      $offer_field = $parameters['offer field'];
      $offer_wrapper = entity_metadata_wrapper('commerce_discount_offer', $offer);
      $offer_wrapper->{$offer_field} = $parameters['offer value'];
      $offer_wrapper->save();

      // Create and save discount.
      $discount = entity_create('commerce_discount', array(
        'type' => 'order_discount',
        'name' => 'pct_discount_' . $parameters['offer value safe'],
        'label' => $parameters['label'],
        'component_title' => $parameters['label']
      ));

      $discount_wrapper = entity_metadata_wrapper('commerce_discount', $discount);
      // Set offer reference.
      $discount_wrapper->commerce_discount_offer = $offer;

      $discount_wrapper->save();
    }

    if ($discount) {
      $conditions = array();
      if (module_exists('commerce_coupon_usage') && !empty($coupon->commerce_coupon_number_of_uses)) {
        // Add an inline condition for number of uses. 
        $conditions[] = array(
          'condition_name' => 'commerce_coupon_usage_evaluate_usage',
          'condition_settings' => array(
            'max_usage' => $coupon_wrapper->commerce_coupon_number_of_uses->value()
          )
        );        
      }
      
      // Set the bundle now.
      $coupon->type = 'discount_coupon';
      
      // Set inline conditions field. Must retrieve the wrapper again because 
      // the bundle has changed.
      $updated_coupon_wrapper = entity_metadata_wrapper('commerce_coupon', $coupon);
      if (!empty($conditions)) {
        $updated_coupon_wrapper->commerce_coupon_conditions[] = $condition;
      }
      
      // Set discount reference and save.
      $coupon->commerce_discount_reference[LANGUAGE_NONE][] = array('target_id' => $discount->discount_id);
      commerce_coupon_save($coupon);
      
      // Rebuild discount rules.
      entity_defaults_rebuild(array('rules_config'));
    }
  }
}

/*
 * Batch finished callback: cleanup after all coupon entities are processed.
 */
function commerce_coupon_update_batch_finished($success, $results, $operations) {
  // Remove fields that we no longer need.
  module_disable(array('commerce_coupon_pct', 'commerce_coupon_fixed_amount'));
}

/*
 * Stub function so that coupon type modules do not crash when they disable.
 */
function commerce_coupon_type_disable() {}